In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('bookings_data.csv')

In [3]:
pd.options.display.max_columns=37

In [4]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

Hotel booking cancellation -

In [5]:
data['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [6]:
data['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [8]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
agent,103050.0,86.693382,110.774548,1.00,9.00,14.000,229.0,535.0
company,6797.0,189.266735,131.655015,6.00,62.00,179.000,270.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [9]:
data.describe(include='O')

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date,name,email,phone-number,credit_card
count,119390,119390,119390,118902,119390,119390,119390,119390,119390,119390,119390,119390,119390,119390,119390,119390
unique,2,12,5,177,8,5,10,12,3,4,3,926,81503,115889,119390,9000
top,City Hotel,August,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-10-21,Michael Johnson,Michael.C@gmail.com,422-804-6403,************3627
freq,79330,13877,92310,48590,56477,97870,85994,74053,104641,89613,75166,1461,48,6,1,28

High cardianality features -

In [10]:
data.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [12]:
cat_col = ['hotel', 'is_canceled',
'arrival_date_year',
'arrival_date_month',
'meal',
'country',
'market_segment',
'distribution_channel',
'is_repeated_guest',
'reserved_room_type',
'assigned_room_type',
'deposit_type',
'agent',
'company',
'customer_type',
'reservation_status',
'name','email',
'phone-number',
'credit_card'
]

In [13]:
for col in cat_col:
    if col in data.columns:
        data[col] = data[col].astype(str)

In [14]:
data.dtypes

hotel                              object
is_canceled                        object
lead_time                           int64
arrival_date_year                  object
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                  object
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                              object
company                            object
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
name                               object
email                              object
phone-number                       object
credit_card                        object
dtype: object

In [15]:
data.describe(include='O').T

                          count  unique                  top    freq
hotel                    119390       2           City Hotel   79330
is_canceled              119390       2                    0   75166
arrival_date_year        119390       3                 2016   56707
arrival_date_month       119390      12               August   13877
meal                     119390       5                   BB   92310
country                  119390     178                  PRT   48590
market_segment           119390       8            Online TA   56477
distribution_channel     119390       5                TA/TO   97870
is_repeated_guest        119390       2                    0  115580
reserved_room_type       119390      10                    A   85994
assigned_room_type       119390      12                    A   74053
deposit_type             119390       3           No Deposit  104641
agent                    119390     334                  9.0   31961
company                  119390     353                  nan  112593
customer_type            119390       4            Transient   89613
reservation_status       119390       3            Check-Out   75166
reservation_status_date  119390     926           2015-10-21    1461
name                     119390   81503      Michael Johnson      48
email                    119390  115889  Michael.C@gmail.com       6
phone-number             119390  119390         422-804-6403       1
credit_card              119390    9000     ************3627      28

In [16]:
data['is_canceled'].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [17]:
data = pd.read_csv('bookings_data.csv')

In [18]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

# Data Leakage:
data is available while training but not available during prediction

In [19]:
data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='object')

In [20]:
data.drop(columns=['arrival_date_year','assigned_room_type','reservation_status', 'reservation_status_date'],
         inplace=True)

In [21]:
data

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,name,email,phone-number,credit_card
0,Resort Hotel,0,342,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [22]:
data.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_month',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'booking_changes', 'deposit_type', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests', 'name',
       'email', 'phone-number', 'credit_card'],
      dtype='object')

In [23]:
high_car = ['country','agent', 'company','name',
       'email', 'phone-number', 'credit_card']
uni = data[high_car].nunique()
nulls = data[high_car].isna().sum()

In [24]:
uni

country            177
agent              333
company            352
name             81503
email           115889
phone-number    119390
credit_card       9000
dtype: int64

In [25]:
high_car_df = pd.DataFrame({'Unique':uni,
                           'Missing values':nulls})

In [26]:
high_car_df

              Unique  Missing values
country          177             488
agent            333           16340
company          352          112593
name           81503               0
email         115889               0
phone-number  119390               0
credit_card     9000               0

In [27]:
data.drop(columns=high_car,inplace=True)

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_month              119390 non-null  object
 4   arrival_date_week_number        119390 non-null  int64
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119386 non-null  float64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  object
 12  market_segment                  119390 non-null  object
 13  distribution_channel            119390 non-null  object
 14  is_repeated_guest               119390 non-null  int64
 15  previous_cancellations          119390 non-null  int64
 16  previous_bookings_not_canceled  119390 non-null  int64
 17  reserved_room_type              119390 non-null  object
 18  booking_changes                 119390 non-null  int64
 19  deposit_type                    119390 non-null  object
 20  days_in_waiting_list            119390 non-null  int64
 21  customer_type                   119390 non-null  object
 22  adr                             119390 non-null  float64
 23  required_car_parking_spaces     119390 non-null  int64
 24  total_of_special_requests       119390 non-null  int64
dtypes: float64(2), int64(15), object(8)
memory usage: 22.8+ MB

In [29]:
data.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [30]:
data['children'] = data['children'].fillna(0)

In [31]:
data.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [32]:
data[data['adults']==0]

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
2224,Resort Hotel,0,1,October,41,6,0,3,0,0.0,0,SC,Corporate,Corporate,0,0,0,A,1,No Deposit,0,Transient-Party,0.00,0,0
2409,Resort Hotel,0,0,October,42,12,0,0,0,0.0,0,SC,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,0.00,0,0
3181,Resort Hotel,0,36,November,47,20,1,2,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,0,No Deposit,0,Transient-Party,0.00,0,0
3684,Resort Hotel,0,165,December,53,30,1,4,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,1,No Deposit,122,Transient-Party,0.00,0,0
3708,Resort Hotel,0,165,December,53,30,2,4,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,1,No Deposit,122,Transient-Party,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117204,City Hotel,0,296,July,30,27,1,3,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,0,No Deposit,0,Transient,98.85,0,1
117274,City Hotel,0,276,July,31,30,2,1,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,1,No Deposit,0,Transient,93.64,0,2
117303,City Hotel,0,291,July,30,29,2,2,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,0,No Deposit,0,Transient,98.85,0,1
117453,City Hotel,0,159,July,31,31,1,3,0,2.0,0,SC,Online TA,TA/TO,0,0,0,A,1,No Deposit,0,Transient,121.88,0,1
118200,City Hotel,0,10,August,32,12,2,2,0,3.0,0,BB,Direct,Direct,0,0,0,B,1,No Deposit,0,Transient-Party,6.00,0,1

In [33]:
noise = {'adr':data[data['adr']<0],
        'adults':data[data['adults']==0],
        'children': data[data['children']==10],
        'babies':data[data['babies']==10]}

In [34]:
noise

{'adr':               hotel  is_canceled  lead_time arrival_date_month  \
 14969  Resort Hotel            0        195              March

        arrival_date_week_number  arrival_date_day_of_month  \
 14969                        10                          5

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
 14969                        4                     6       2       0.0

        babies meal market_segment distribution_channel  is_repeated_guest  \
 14969       0   BB         Groups               Direct                  1

        previous_cancellations  previous_bookings_not_canceled  \
 14969                       0                               2

       reserved_room_type  booking_changes deposit_type  days_in_waiting_list  \
 14969                  A                2   No Deposit                     0

          customer_type   adr  required_car_parking_spaces  \
 14969  Transient-Party -6.38                            0

        total_of_special_requests
 14969                          0  ,
 'adults':                hotel  is_canceled  lead_time arrival_date_month  \
 2224    Resort Hotel            0          1            October
 2409    Resort Hotel            0          0            October
 3181    Resort Hotel            0         36           November
 3684    Resort Hotel            0        165           December
 3708    Resort Hotel            0        165           December
 ...              ...          ...        ...                ...
 117204    City Hotel            0        296               July
 117274    City Hotel            0        276               July
 117303    City Hotel            0        291               July
 117453    City Hotel            0        159               July
 118200    City Hotel            0         10             August

         arrival_date_week_number  arrival_date_day_of_month  \
 2224                          41                          6
 2409                          42                         12
 3181                          47                         20
 3684                          53                         30
 3708                          53                         30
 ...                          ...                        ...
 117204                        30                         27
 117274                        31                         30
 117303                        30                         29
 117453                        31                         31
 118200                        32                         12

         stays_in_weekend_nights  stays_in_week_nights  adults  children  \
 2224                          0                     3       0       0.0
 2409                          0                     0       0       0.0
 3181                          1                     2       0       0.0
 3684                          1                     4       0       0.0
 3708                          2                     4       0       0.0
 ...                         ...                   ...     ...       ...
 117204                        1                     3       0       2.0
 117274                        2                     1       0       2.0
 117303                        2                     2       0       2.0
 117453                        1                     3       0       2.0
 118200                        2                     2       0       3.0

         babies meal market_segment distribution_channel  is_repeated_guest  \
 2224         0   SC      Corporate            Corporate                  0
 2409         0   SC      Corporate            Corporate                  0
 3181         0   SC         Groups                TA/TO                  0
 3684         0   SC         Groups                TA/TO                  0
 3708         0   SC         Groups                TA/TO                  0
 ...        ...  ...            ...                  ...                ...
 117204       0   BB      Online TA                TA/TO                  0
 117274       0   BB      Online TA                TA/TO                  0
 117303       0   BB      Online TA                TA/TO                  0
 117453       0   SC      Online TA                TA/TO                  0
 118200       0   BB         Direct               Direct                  0

         previous_cancellations  previous_bookings_not_canceled  \
 2224                         0                               0
 2409                         0                               0
 3181                         0                               0
 3684                         0                               0
 3708                         0                               0
 ...                        ...                             ...
 117204                       0                               0
 117274                       0                               0
 117303                       0                               0
 117453                       0                               0
 118200                       0                               0

        reserved_room_type  booking_changes deposit_type  days_in_waiting_list  \
 2224                    A                1   No Deposit                     0
 2409                    A                0   No Deposit                     0
 3181                    A                0   No Deposit                     0
 3684                    A                1   No Deposit                   122
 3708                    A                1   No Deposit                   122
 ...                   ...              ...          ...                   ...
 117204                  B                0   No Deposit                     0
 117274                  B                1   No Deposit                     0
 117303                  B                0   No Deposit                     0
 117453                  A                1   No Deposit                     0
 118200                  B                1   No Deposit                     0

           customer_type     adr  required_car_parking_spaces  \
 2224    Transient-Party    0.00                            0
 2409          Transient    0.00                            0
 3181    Transient-Party    0.00                            0
 3684    Transient-Party    0.00                            0
 3708    Transient-Party    0.00                            0
 ...                 ...     ...                          ...
 117204        Transient   98.85                            0
 117274        Transient   93.64                            0
 117303        Transient   98.85                            0
 117453        Transient  121.88                            0
 118200  Transient-Party    6.00                            0

         total_of_special_requests
 2224                            0
 2409                            0
 3181                            0
 3684                            0
 3708                            0
 ...                           ...
 117204                          1
 117274                          2
 117303                          1
 117453                          1
 118200                          1

 [403 rows x 25 columns],
 'children':             hotel  is_canceled  lead_time arrival_date_month  \
 328  Resort Hotel            1         55               July

      arrival_date_week_number  arrival_date_day_of_month  \
 328                        29                         12

      stays_in_weekend_nights  stays_in_week_nights  adults  children  babies  \
 328                        4                    10       2      10.0       0

     meal market_segment distribution_channel  is_repeated_guest  \
 328   BB  Offline TA/TO                TA/TO                  0

      previous_cancellations  previous_bookings_not_canceled  \
 328                       0                               0

     reserved_room_type  booking_changes deposit_type  days_in_waiting_list  \
 328                  D                2   No Deposit                     0

     customer_type     adr  required_car_parking_spaces  \
 328      Contract  133.16                            0

      total_of_special_requests
 328                          1  ,
 'babies':             hotel  is_canceled  lead_time arrival_date_month  \
 46619  City Hotel            0         37            January

        arrival_date_week_number  arrival_date_day_of_month  \
 46619                         3                         12

        stays_in_weekend_nights  stays_in_week_nights  adults  children  \
 46619                        0                     2       2       0.0

        babies meal market_segment distribution_channel  is_repeated_guest  \
 46619      10   BB      Online TA                TA/TO                  0

        previous_cancellations  previous_bookings_not_canceled  \
 46619                       0                               0

       reserved_room_type  booking_changes deposit_type  days_in_waiting_list  \
 46619                  D                1   No Deposit                     0

       customer_type    adr  required_car_parking_spaces  \
 46619     Transient  84.45                            0

        total_of_special_requests
 46619                          1  }

In [35]:
noise_data = {i:len(j) for i,j in noise.items()}

In [36]:
noise_data

{'adr': 1, 'adults': 403, 'children': 1, 'babies': 1}

In [39]:
noise['adults']

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
2224,Resort Hotel,0,1,October,41,6,0,3,0,0.0,0,SC,Corporate,Corporate,0,0,0,A,1,No Deposit,0,Transient-Party,0.00,0,0
2409,Resort Hotel,0,0,October,42,12,0,0,0,0.0,0,SC,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,0.00,0,0
3181,Resort Hotel,0,36,November,47,20,1,2,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,0,No Deposit,0,Transient-Party,0.00,0,0
3684,Resort Hotel,0,165,December,53,30,1,4,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,1,No Deposit,122,Transient-Party,0.00,0,0
3708,Resort Hotel,0,165,December,53,30,2,4,0,0.0,0,SC,Groups,TA/TO,0,0,0,A,1,No Deposit,122,Transient-Party,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117204,City Hotel,0,296,July,30,27,1,3,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,0,No Deposit,0,Transient,98.85,0,1
117274,City Hotel,0,276,July,31,30,2,1,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,1,No Deposit,0,Transient,93.64,0,2
117303,City Hotel,0,291,July,30,29,2,2,0,2.0,0,BB,Online TA,TA/TO,0,0,0,B,0,No Deposit,0,Transient,98.85,0,1
117453,City Hotel,0,159,July,31,31,1,3,0,2.0,0,SC,Online TA,TA/TO,0,0,0,A,1,No Deposit,0,Transient,121.88,0,1
118200,City Hotel,0,10,August,32,12,2,2,0,3.0,0,BB,Direct,Direct,0,0,0,B,1,No Deposit,0,Transient-Party,6.00,0,1

In [43]:
data

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,July,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,3,No Deposit,0,Transient,0.00,0,0
1,Resort Hotel,0,737,July,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,4,No Deposit,0,Transient,0.00,0,0
2,Resort Hotel,0,7,July,27,1,0,1,1,0.0,0,BB,Direct,Direct,0,0,0,A,0,No Deposit,0,Transient,75.00,0,0
3,Resort Hotel,0,13,July,27,1,0,1,1,0.0,0,BB,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,75.00,0,0
4,Resort Hotel,0,14,July,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,August,35,30,2,5,2,0.0,0,BB,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,0,Transient,96.14,0,0
119386,City Hotel,0,102,August,35,31,2,5,3,0.0,0,BB,Online TA,TA/TO,0,0,0,E,0,No Deposit,0,Transient,225.43,0,2
119387,City Hotel,0,34,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,D,0,No Deposit,0,Transient,157.71,0,4
119388,City Hotel,0,109,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,104.40,0,0
119389,City Hotel,0,205,August,35,29,2,7,2,0.0,0,HB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,151.20,0,2

In [42]:
noise['adults'].index

Index([  2224,   2409,   3181,   3684,   3708,   4127,   9376,  31765,  32029,
        32827,
       ...
       116558, 116832, 117087, 117128, 117130, 117204, 117274, 117303, 117453,
       118200],
      dtype='int64', length=403)

In [ ]:
data

In [44]:
for i in noise.keys():
    data.drop(noise[i].index,inplace=True)

In [47]:
data.drop([0,1,2])

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
3,Resort Hotel,0,13,July,27,1,0,1,1,0.0,0,BB,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,75.00,0,0
4,Resort Hotel,0,14,July,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,98.00,0,1
5,Resort Hotel,0,14,July,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,98.00,0,1
6,Resort Hotel,0,0,July,27,1,0,2,2,0.0,0,BB,Direct,Direct,0,0,0,C,0,No Deposit,0,Transient,107.00,0,0
7,Resort Hotel,0,9,July,27,1,0,2,2,0.0,0,FB,Direct,Direct,0,0,0,C,0,No Deposit,0,Transient,103.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,August,35,30,2,5,2,0.0,0,BB,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,0,Transient,96.14,0,0
119386,City Hotel,0,102,August,35,31,2,5,3,0.0,0,BB,Online TA,TA/TO,0,0,0,E,0,No Deposit,0,Transient,225.43,0,2
119387,City Hotel,0,34,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,D,0,No Deposit,0,Transient,157.71,0,4
119388,City Hotel,0,109,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,104.40,0,0
119389,City Hotel,0,205,August,35,29,2,7,2,0.0,0,HB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,151.20,0,2

In [48]:
noise_after_handling = {'adr':data[data['adr']<0],
        'adults':data[data['adults']==0],
        'children': data[data['children']==10],
        'babies':data[data['babies']==10]}

In [49]:
noise_after_handling

{'adr': Empty DataFrame
 Columns: [hotel, is_canceled, lead_time, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, booking_changes, deposit_type, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests]
 Index: [],
 'adults': Empty DataFrame
 Columns: [hotel, is_canceled, lead_time, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, booking_changes, deposit_type, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests]
 Index: [],
 'children': Empty DataFrame
 Columns: [hotel, is_canceled, lead_time, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, booking_changes, deposit_type, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests]
 Index: [],
 'babies': Empty DataFrame
 Columns: [hotel, is_canceled, lead_time, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, booking_changes, deposit_type, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests]
 Index: []}

In [50]:
{i:len(j) for i,j in noise_after_handling.items()}

{'adr': 0, 'adults': 0, 'children': 0, 'babies': 0}

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118984 entries, 0 to 119389
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118984 non-null  object
 1   is_canceled                     118984 non-null  int64
 2   lead_time                       118984 non-null  int64
 3   arrival_date_month              118984 non-null  object
 4   arrival_date_week_number        118984 non-null  int64
 5   arrival_date_day_of_month       118984 non-null  int64
 6   stays_in_weekend_nights         118984 non-null  int64
 7   stays_in_week_nights            118984 non-null  int64
 8   adults                          118984 non-null  int64
 9   children                        118984 non-null  float64
 10  babies                          118984 non-null  int64
 11  meal                            118984 non-null  object
 12  market_segment                  118984 non-null  object
 13  distribution_channel            118984 non-null  object
 14  is_repeated_guest               118984 non-null  int64
 15  previous_cancellations          118984 non-null  int64
 16  previous_bookings_not_canceled  118984 non-null  int64
 17  reserved_room_type              118984 non-null  object
 18  booking_changes                 118984 non-null  int64
 19  deposit_type                    118984 non-null  object
 20  days_in_waiting_list            118984 non-null  int64
 21  customer_type                   118984 non-null  object
 22  adr                             118984 non-null  float64
 23  required_car_parking_spaces     118984 non-null  int64
 24  total_of_special_requests       118984 non-null  int64
dtypes: float64(2), int64(15), object(8)
memory usage: 27.6+ MB

In [55]:
cat = [i for i in data.columns if data[i].dtype=='O']

In [56]:
cat

['hotel',
 'arrival_date_month',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'deposit_type',
 'customer_type']

In [57]:
ohe = [i for i in cat if i != 'arrival_date_month']

In [58]:
ohe

['hotel',
 'meal',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'deposit_type',
 'customer_type']

In [59]:
data = pd.get_dummies(data,columns=ohe,dtype=int)

In [60]:
data

,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,...,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,July,27,1,0,0,2,0.0,0,0,0,0,3,0,0.00,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,737,July,27,1,0,0,2,0.0,0,0,0,0,4,0,0.00,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
2,0,7,July,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,13,July,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,0,14,July,27,1,0,2,2,0.0,0,0,0,0,0,0,98.00,0,1,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,August,35,30,2,5,2,0.0,0,0,0,0,0,0,96.14,0,0,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,0,102,August,35,31,2,5,3,0.0,0,0,0,0,0,0,225.43,0,2,...,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
119387,0,34,August,35,31,2,5,2,0.0,0,0,0,0,0,0,157.71,0,4,...,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119388,0,109,August,35,31,2,5,2,0.0,0,0,0,0,0,0,104.40,0,0,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,0,205,August,35,29,2,7,2,0.0,0,0,0,0,0,0,151.20,0,2,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [61]:
data['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [62]:
month = {'July':7, 'August':8, 'September':9, 'October':10, 'November':11, 'December':12,
       'January':1, 'February':2, 'March':3, 'April':4, 'May':5, 'June':6}

In [63]:
data['arrival_date_month'] = data['arrival_date_month'].map(month)

In [64]:
data

,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,...,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,7,27,1,0,0,2,0.0,0,0,0,0,3,0,0.00,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,737,7,27,1,0,0,2,0.0,0,0,0,0,4,0,0.00,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
2,0,7,7,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,13,7,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,0,14,7,27,1,0,2,2,0.0,0,0,0,0,0,0,98.00,0,1,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,8,35,30,2,5,2,0.0,0,0,0,0,0,0,96.14,0,0,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,0,102,8,35,31,2,5,3,0.0,0,0,0,0,0,0,225.43,0,2,...,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
119387,0,34,8,35,31,2,5,2,0.0,0,0,0,0,0,0,157.71,0,4,...,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119388,0,109,8,35,31,2,5,2,0.0,0,0,0,0,0,0,104.40,0,0,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,0,205,8,35,29,2,7,2,0.0,0,0,0,0,0,0,151.20,0,2,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118984 entries, 0 to 119389
Data columns (total 54 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     118984 non-null  int64
 1   lead_time                       118984 non-null  int64
 2   arrival_date_month              118984 non-null  int64
 3   arrival_date_week_number        118984 non-null  int64
 4   arrival_date_day_of_month       118984 non-null  int64
 5   stays_in_weekend_nights         118984 non-null  int64
 6   stays_in_week_nights            118984 non-null  int64
 7   adults                          118984 non-null  int64
 8   children                        118984 non-null  float64
 9   babies                          118984 non-null  int64
 10  is_repeated_guest               118984 non-null  int64
 11  previous_cancellations          118984 non-null  int64
 12  previous_bookings_not_canceled  118984 non-null  int64
 13  booking_changes                 118984 non-null  int64
 14  days_in_waiting_list            118984 non-null  int64
 15  adr                             118984 non-null  float64
 16  required_car_parking_spaces     118984 non-null  int64
 17  total_of_special_requests       118984 non-null  int64
 18  hotel_City Hotel                118984 non-null  int64
 19  hotel_Resort Hotel              118984 non-null  int64
 20  meal_BB                         118984 non-null  int64
 21  meal_FB                         118984 non-null  int64
 22  meal_HB                         118984 non-null  int64
 23  meal_SC                         118984 non-null  int64
 24  meal_Undefined                  118984 non-null  int64
 25  market_segment_Aviation         118984 non-null  int64
 26  market_segment_Complementary    118984 non-null  int64
 27  market_segment_Corporate        118984 non-null  int64
 28  market_segment_Direct           118984 non-null  int64
 29  market_segment_Groups           118984 non-null  int64
 30  market_segment_Offline TA/TO    118984 non-null  int64
 31  market_segment_Online TA        118984 non-null  int64
 32  market_segment_Undefined        118984 non-null  int64
 33  distribution_channel_Corporate  118984 non-null  int64
 34  distribution_channel_Direct     118984 non-null  int64
 35  distribution_channel_GDS        118984 non-null  int64
 36  distribution_channel_TA/TO      118984 non-null  int64
 37  distribution_channel_Undefined  118984 non-null  int64
 38  reserved_room_type_A            118984 non-null  int64
 39  reserved_room_type_B            118984 non-null  int64
 40  reserved_room_type_C            118984 non-null  int64
 41  reserved_room_type_D            118984 non-null  int64
 42  reserved_room_type_E            118984 non-null  int64
 43  reserved_room_type_F            118984 non-null  int64
 44  reserved_room_type_G            118984 non-null  int64
 45  reserved_room_type_H            118984 non-null  int64
 46  reserved_room_type_L            118984 non-null  int64
 47  deposit_type_No Deposit         118984 non-null  int64
 48  deposit_type_Non Refund         118984 non-null  int64
 49  deposit_type_Refundable         118984 non-null  int64
 50  customer_type_Contract          118984 non-null  int64
 51  customer_type_Group             118984 non-null  int64
 52  customer_type_Transient         118984 non-null  int64
 53  customer_type_Transient-Party   118984 non-null  int64
dtypes: float64(2), int64(52)
memory usage: 54.0 MB

In [66]:
data['is_canceled']

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: is_canceled, Length: 118984, dtype: int64

In [67]:
X = data.drop('is_canceled',axis=1)
y = data['is_canceled']

In [68]:
X

,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,...,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,342,7,27,1,0,0,2,0.0,0,0,0,0,3,0,0.00,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
1,737,7,27,1,0,0,2,0.0,0,0,0,0,4,0,0.00,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
2,7,7,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,13,7,27,1,0,1,1,0.0,0,0,0,0,0,0,75.00,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,14,7,27,1,0,2,2,0.0,0,0,0,0,0,0,98.00,0,1,0,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,23,8,35,30,2,5,2,0.0,0,0,0,0,0,0,96.14,0,0,1,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,102,8,35,31,2,5,3,0.0,0,0,0,0,0,0,225.43,0,2,1,...,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
119387,34,8,35,31,2,5,2,0.0,0,0,0,0,0,0,157.71,0,4,1,...,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119388,109,8,35,31,2,5,2,0.0,0,0,0,0,0,0,104.40,0,0,1,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,205,8,35,29,2,7,2,0.0,0,0,0,0,0,0,151.20,0,2,1,...,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [69]:
y

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: is_canceled, Length: 118984, dtype: int64

In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [72]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\saiar\appdata\roaming\python\python312\site-packages (from xgboost) (2.2.4)
Requirement already satisfied: scipy in c:\users\saiar\appdata\roaming\python\python312\site-packages (from xgboost) (1.16.2)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   - -------------------------------------- 2.1/48.9 MB 11.7 MB/s eta 0:00:05
   --- ------------------------------------ 4.5/48.9 MB 11.7 MB/s eta 0:00:04
   ----- ---------------------------------- 6.8/48.9 MB 11.6 MB/s eta 0:00:04
   ------- -------------------------------- 9.2/48.9 MB 11.4 MB/s eta 0:00:04
   --------- ------------------------------ 11.5/48.9 MB 11.4 MB/s eta 0:00:04
   ----------- ---------------------------- 13.9/48.9 MB 11.5 MB/s eta 0:00:04
   ------------- -------------------------- 16.0/48.9 MB 11.4 MB/s eta 0:00:03
   -------------- ------------------------- 18.4/48.9 MB 11.5 MB/s eta 0:00:03
   ---------------- ----------------------- 20.4/48.9 MB 11.3 MB/s eta 0:00:03
   ------------------ --------------------- 22.5/48.9 MB 11.2 MB/s eta 0:00:03
   -------------------- ------------------- 24.9/48.9 MB 11.3 MB/s eta 0:00:03
   ---------------------- ----------------- 27.0/48.9 MB 11.3 MB/s eta 0:00:02
   ----------------------- ---------------- 28.8/48.9 MB 11.1 MB/s eta 0:00:02
   ------------------------- -------------- 31.2/48.9 MB 11.1 MB/s eta 0:00:02
   -------------------------- ------------- 32.8/48.9 MB 10.9 MB/s eta 0:00:02
   ---------------------------- ----------- 35.1/48.9 MB 10.9 MB/s eta 0:00:02
   ------------------------------ --------- 37.5/48.9 MB 11.0 MB/s eta 0:00:02
   -------------------------------- ------- 39.8/48.9 MB 11.0 MB/s eta 0:00:01
   ---------------------------------- ----- 41.9/48.9 MB 11.0 MB/s eta 0:00:01
   ------------------------------------ --- 44.3/48.9 MB 11.0 MB/s eta 0:00:01
   ------------------------------------- -- 45.6/48.9 MB 10.9 MB/s eta 0:00:01
   -------------------------------------- - 46.7/48.9 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 10.1 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,f1_score

In [74]:
def tuning(cls,params):
    cv = StratifiedKFold(n_splits=5,shuffle=True)
    class_grid = GridSearchCV(cls,params,cv=cv,scoring='f1',n_jobs=-1)
    class_grid.fit(X_train,y_train)
    best_hp = class_grid.best_params_
    return class_grid.best_estimator_,best_hp

In [75]:
dt = DecisionTreeClassifier()

In [76]:
dt_parameter_grid = {
    'criterion':['gini','entropy'],
    'max_depth':[12,15,20]
}

In [77]:
tuning(dt,dt_parameter_grid)

(DecisionTreeClassifier(max_depth=20), {'criterion': 'gini', 'max_depth': 20})

In [80]:
dt = DecisionTreeClassifier(criterion= 'gini', max_depth= 20)

In [81]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=20)

In [82]:
y_pred = dt.predict(X_test)

In [83]:
accuracy_score(y_test,y_pred)

0.8279615077530781